title: <p align="center"> Abhishek Joshi </p>
description: 
  <p align="center">
  <a href style="color: white>Resume</a> |
  <a href="https://www.linkedin.com/in/abhishek-joshi-ba7b0385?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BjD%2FXQa4BQWyoA58sDlf3mA%3D%3D" style="color: white>LinkedIn</a> |
  <a href="https://github.com/shibhi61h" style="color: white>GitHub</a>

  <br>
  Hi, Good to see you landing on my page. 
  I am currently working as system design engineer at AMD. This page contains my portfolio related to ML projects.
  I have done some projects such as facial detection in my college with openCV.
  I have total experience of 2 year in frontend VLSI domain.
  <br>
  </p>
  
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
